### ISSUE TITLE
Request: Show fewer browsers

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#1]
We are showing a lot of browsers that support certain features. However, most users are on a particular browser, and if a latest version of that browser supports the requested feature, only return that value. If there is no support for that feature among any version of the browser, return the list of other browsers that support that feature.

**Comment by jonathantneal** [comment]
I think this will be addressed with an option to either show things "display" based, meaning display that feature's supported browsers (like caniuse current works), or "detect" based, meaning we detect/sniff their browser and report if it can use that feature.

**Comment by nimbupani** [comment]
oo sounds good!

**Comment by jonathantneal** [comment]
Compare the results.

#### Something for everyone.

http://sandbox.thewikies.com/caniuse/canvas+json.html
- IE6 and IE7 will be prompted "Almost there! Please update your browser to support the requested features."
- Other browsers will be prompted "Congratulations! Your browser supports the requested features."

---

http://sandbox.thewikies.com/caniuse/apng.html
- Firefox and Opera will be prompted "Congratulations! Your browser supports the requested features."
- Other browsers will be prompted "Oh no! Please use another browser to use the requested features."

---

#### Petite payloads.

http://sandbox.thewikies.com/caniuse/apng.js
- payload is way smaller

``` json
{"client":{"id":"chrome","name":"Chrome","version":"16.0.912.77","mobile":false,"supported":false},"browsers":[{"id":"firefox","name":"Firefox","version":"3","url":"http:\/\/www.firefox.com\/"},{"id":"opera","name":"Opera","version":"9.5","url":"http:\/\/www.opera.com\/"},{"id":"op_mob","name":"Opera Mobile","version":"10","url":"http:\/\/www.opera.com\/mobile\/"}]}
```

---

#### Very custom payloads with HTML.

http://sandbox.thewikies.com/caniuse/apng.html?callback=myFunction&text

``` json
myFunction({"client":{"id":"chrome","name":"Chrome","version":"16.0.912.77","mobile":false,"supported":false},"browsers":[{"id":"firefox","name":"Firefox","version":"3","url":"http:\/\/www.firefox.com\/"},{"id":"opera","name":"Opera","version":"9.5","url":"http:\/\/www.opera.com\/"},{"id":"op_mob","name":"Opera Mobile","version":"10","url":"http:\/\/www.opera.com\/mobile\/"}],"html":"<div class=\\\"caniuse\\\"><p class=\\\"caniuse-message\\\">Oh no! Please use another browser to use the requested features.<\/p><p class=\\\"caniuse-browser\\\"><a class=\\\"caniuse-link\\\" href=\\\"http:\/\/www.firefox.com\/\\\" rel=\\\"external\\\" target=\\\"_blank\\\">Firefox<\/a> or <a class=\\\"caniuse-link\\\" href=\\\"http:\/\/www.opera.com\/\\\" rel=\\\"external\\\" target=\\\"_blank\\\">Opera<\/a> or <a class=\\\"caniuse-link\\\" href=\\\"http:\/\/www.opera.com\/mobile\/\\\" rel=\\\"external\\\" target=\\\"_blank\\\">Opera Mobile<\/a><\/p><\/div>"})
```

---

If this addresses your concerns, please close the issue. :D

**Comment by nimbupani** [comment]
Does the 'update your browser' come with a link? Also the 'other browsers'  in 'Oh no! Please use another browser…' could link to http://browsehappy.com

**Comment by jonathantneal** [comment]
When there is an update for the client browser, then yes, the update page includes a link to that browser's landing page so they can grab the latest version.

When there is only the option of another browser, the other browsers which also include links to their landing pages.  I would be happy to setup a link to browsehappy, but I'm not sure if it's needed as long as we're both forwarding users to the same pages.

**Comment by AaronLayton** [comment]
I like the way it currently is where we link straight to the browser download page. Linking to another site would just create an extra click the end user would have to do to get their browser updated

**Comment by nimbupani** [comment]
What we have matches what I had in mind. Thanks @jonathantneal !
