### ISSUE TITLE
Modernizr plugin

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#11]
@paulirish can we have this ready and have it advertisable on the main page?

**Comment by paulirish** [comment]
Yup we will

**Comment by nimbupani** [comment]
https://etherpad.mozilla.org/supportedbrowsersapi

**Comment by paulirish** [comment]
Complete: https://gist.github.com/1896401

**Comment by nimbupani** [comment]
Currently referenced from main page to this gist? should it go elsewhere? Should be included in modernizr builder?

**Comment by addyosmani** [comment]
@nimbupani it's currently in the index below 'use'  http://addyosmani.com/gyazo/77cd99.png. I would personally make it a little more visible because I can see quite a few people wanting to opt for the Modernizr plugin version. If you guys decide it needs its own section, I don't mind helping with some dialog around it, unless Paul would like to do that :)

**Comment by nimbupani** [comment]
@paulirish @addyosmani could you look into the widget snippet and let me know why its not working? If you would commit a fix that would be great too.

**Comment by addyosmani** [comment]
@nimbupani just confirming: widget snippet still broken? I took a look at Modernizr + the plugin snippet + necessary markup earlier and it didn't seem to be working (tested Opera/Chome). If it's still borked I can take another look and figure out what's wrong.

**Comment by nimbupani** [comment]
I think @paulirish is working on it at this moment.

**Comment by addyosmani** [comment]
Thats cool. If you guys need any further help with it, feel free to let me know :) I was going to do some more work on demos and I think there's an open issue for more documentation. Is anyone working on that?

**Comment by nimbupani** [comment]
Addy, nobody is as far as I know. I would love to have some. Simurai has already included some of it in his projects I notice: http://lab.simurai.com/flashlight/ and http://lab.simurai.com/carveme/

**Comment by addyosmani** [comment]
Sahweet. Thanks. I'll ping you guys as soon as I have something useful ready.

**Comment by paulirish** [comment]
modernizr plugin done. it's in the repo, too.
