### ISSUE TITLE
Tweak html output

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#14]
"upgrade" is a bit strong especially for unstable features. We should say "use". 

All information about browsers should be presented without hover, because this is essential info that shouldn't be hidden.

**Comment by jonathantneal** [comment]
I agree. I'd like to adjust the language to be less strong as well.

**Comment by nimbupani** [comment]
Example: http://h5bp.github.com/caniuse/test.html

**Comment by nimbupani** [comment]
Done in 4e9a979237e277b0a71a5ad2f8d0cb85f5c6caca
