### ISSUE TITLE
Design to dos

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#15]
- <del>Adjust space when there are no options (e.g. XML format)</del>
- <del>Autocomplete drop-down is fugly. Needs fixing.</del>
- <del>Builders section needs more tweaks.</del>
- Test it in all mobile devices. 
- <del>Show the 'more info'</del>
- <del>Move html to be first option in format</del>
- <del>Make text&icon option to be default as button option. </del>

**Comment by AaronLayton** [comment]
@nimbupani what mobile devices does it need testing on? I have Android and iOS at hand or are you thinking more device specific not OS specific?

**Comment by nimbupani** [comment]
Essentially Opera Mobile/Mini/Firefox Mobile/Chrome for Android/Android/Mobile Safari of dominant versions would do.

**Comment by drublic** [comment]
At the moment on mobile the desktop version of the page is displayed, as you can see here:

![iOS Safari screenshot](http://dl.dropbox.com/u/8455906/h5bp-caniuse-ios-safari.png)

I think devs mostly visit this page with a desktop computer. Anyway a mobile version would ne nice. Plans?

**Edit:** Figured it. Viewport-meta is missing.
