### ISSUE TITLE
Do we need a congratulations message?

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#16]
I think ideally the html should show nothing if the browser supports the features required. The intent is to get out of the way of users when not necessary. The prompt and html should only render if the features are not supported.

**Comment by paulirish** [comment]
Yeah empty string payload if current browser passes. good call.

**Comment by addyosmani** [comment]
Agreed. 

When I was putting together demos using what we have now I didn't see a need to display a congrats message either. As @nimbupani says, let's stay out of users ways where possible :)

**Comment by nimbupani** [comment]
Fixed. 4e9a979237e277b0a71a5ad2f8d0cb85f5c6caca

**Comment by addyosmani** [comment]
\o/
