### ISSUE TITLE
Should only recommend desktop browsers for desktop requests

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#17]
Currently it recommends all browsers mobile/desktop if request comes from Desktop agents. We should only recommend desktop browsers.

Likewise with mobile UAs.

**Comment by paulirish** [comment]
:+1:

**Comment by paulirish** [comment]
Mobile I can see a case where recommending desktop makes sense. I can't view the site on my phone, but I should be able to use my desktop with its recommendation.

**Comment by nimbupani** [comment]
Agreed but only if none of the mobile browsers are capable of rendering it, the messaging should be tweaked to ask users to view on a desktop-ish device.

**Comment by paulirish** [comment]
If you're on iOS it doesn't help you to tell you that Opera Mobile can show
it. :)

Now if we actually want to deal with facts like this, then that's another
story..

**Comment by nimbupani** [comment]
Yeah good point. I guess then when on mobile we show mobile browsers + desktop.

**Comment by nimbupani** [comment]
cc: @beverloo

**Comment by paulirish** [comment]
Another one.. 

If i'm on Firefox 3.6, it needs to tell me to upgrade to.. er.. "use" Firefox 10. Just the icon makes me as a user go WTF.

**Comment by nimbupani** [comment]
Fixed by fadf4eb37b718921c4ddf98f8b55563712bad870
