### ISSUE TITLE
Should show link to latest browser version that supports a feature

### ISSUE THREAD

**Issue by nimbupani** [h5bp/html5please-api#18]
E.g. [cors](http://sandbox.thewikies.com/caniuse/cors.html?) in Opera Stable tells me to download other browsers, but Opera Next supports Cors, ideally it should ask users to download that.

**Comment by paulirish** [comment]
But it should show all. e.g. If Chrome stable doesnt have it, Beta does... and so does Firefox stable... I'd much rather open Firefox than replace my Chrome stable install with a non-sidebyside beta.

**Comment by nimbupani** [comment]
Yeah sgtm.

**Comment by nimbupani** [comment]
cc: @beverloo

**Comment by nimbupani** [comment]
Okay after talking with @jonathantneal sounds like this is wayy too complicated and unnecessary. Tabling this for now, not essential for launch.
