### ISSUE TITLE
test pages

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#2]
i think its time to make some test pages. using the JSON and mashing it against handlebars

or the HTML and tossing it into a jquery ui dialog

whatever we expect people to do with this service

that way we'll have demos to show and make sure our JSON data is ideal

Lets find a few HTML5 demos, apps that we can envision things for: http://www.dropmocks.com/ and chrome.angrybirds.com and .. mothereffinghsl.com

**Comment by addyosmani** [comment]
Working on two tests using the JSON data atm. Is it cool for us to PR with http://sandbox.thewikies.com/caniuse/ as the data source until we get a proper host or should we just hold off until we do?

**Comment by paulirish** [comment]
totes cool.

**Comment by addyosmani** [comment]
Sahweet

**Comment by AaronLayton** [comment]
@paulirish Ok to put on some jsfiddles I did? or are you looking more at full website like the ones you listed above?

**Comment by paulirish** [comment]
fiddles are great yes!

btw the script is now in use at http://mothereffinganimatedgif.com/ .. see Safari or mobile safari for it in action.

**Comment by paulirish** [comment]
I'd like to launch with a real demo of this available on a few more sites. I can put it on the other mothereffing's but that seems overkill. other suggestions?

**Comment by addyosmani** [comment]
@paulirish It likely already has a solution in place, but what about html5rocks? Seems like a relatively high-profile site that could demonstrate this in action and it does afaik use feature detection and notify if something is supported or not.

Also, maybe it would make sense for us to find some decent demos relying on HTML5/modern features and see if we can get them to include this.

**Comment by AaronLayton** [comment]
@paulirish @addyosmani Maybe we should look around on chromeexperiments and see if any of the developers on there would be willing to add it to their experiments? Or even check out the DemoStudio over at Mozilla?

**Comment by addyosmani** [comment]
@AaronLayton I think that's a great idea. Definitely worth exploring at least!

**Comment by AaronLayton** [comment]
You want me to fire out some emails and see if I can entice any of them to add it?

**Comment by addyosmani** [comment]
@AaronLayton If you could that would be awesome.
