### ISSUE TITLE
Expose features required subtly

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#20]
Agreed most users dont need to see them, but it can be frustrating that its not accessible at all.

proposal: http://paulirish.com/i/108a30.png

This would help to deal with the "what about safari/opera?" questions that we saw here: http://news.ycombinator.com/item?id=3602160

**Comment by nimbupani** [comment]
sgtm. All that is required is to tweak the features placeholder to output in title attr.

**Comment by paulirish** [comment]
groovy. i'll do it

**Comment by nimbupani** [comment]
Fixed by ad24366c4fd65c0de74807a0144908ed8cc16390
