### ISSUE TITLE
docs: clarify how we recommend browsers

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#21]
we put a lot of logic into how we recommend browsers
- no IE recommendation if you're on mobile or mac/linux
- no mobile browsers if you're on desktop
- it's conditional on what your current browser is (somehow..)

I think these are all very useful. we should document them on the homepage so people understand the value of the service

**Comment by drublic** [comment]
I tried to write something for this. Maybe it helps:

<hr>

## How do we recommend browsers?

As we display browsers we recommend to use for a certain feature the API needs to detect the current user-setup. We do not just recommend every capable browser with a valuable marked share but we try to provide a recommendation for the current site's needs.

As explained above the API detects the user-setup which is done by plain UA-string-sniffing - wait, what?! Browser-sniffing? Yes, right! In this case it's necessary and not evil - the device and the OS are needed to know which browser to recomment to the user.

So how does the API decide which browser to recommend?<br>
**Device:** No mobile browser will be recommended if you are on a desktop computer. And also vice versa.<br>
**Operating System:** If you are on a Mac or Linux the API will not display Internet Explorer as recommended as there is no current version for IE on these platforms.

**Comment by nimbupani** [comment]
On second thoughts, I think it would be useful to publish this on the home page but throw everything else into the wiki. [Current text for this section](https://github.com/h5bp/caniuse/wiki/How-does-the-UA-Detection-work%3F)

**Comment by nimbupani** [comment]
Done in df498d817fa707cf7f306b7be9d66025770b21a5
