### ISSUE TITLE
features focus/blur bug with url builder

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#23]
bug from @benschwarz :
- click into features
- type `can`
- click canvas
- autocomplete guy goes away

It should reset to open and all things available until you blur out of the input.

**Comment by addyosmani** [comment]
+1. I was about to report the same issue. Glad someone got to it before me :)

**Comment by drublic** [comment]
This can be fixed with the snipped below in `script.js` - line 58 before `return false;`

``` javascript
var $that = $(this);
setTimeout(function() {
    $that.trigger('focus');
}, 0);
```

I don't like this idea as it's ugly…
Also: A flash in which the picker is not displayed remains.
