### ISSUE TITLE
show real output (of builder) next to the docs for output

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#24]
> the "output" section might be better if it had an example of the json within it
> so you could see a real looking example of the current query

via @benschwarz

**Comment by addyosmani** [comment]
Did some work on this (assumed you meant a live preview of the current query and not just an example of output) :)

Preview: ![Screenshot](http://addyosmani.com/gyazo/cc578.png)

Did we want syntax highlighting in there? (sure @nimbupani could improve how this looks)

Also @jonathantneal, I was hoping the HTML output could be previewed too but unless I'm mistaken http://sandbox.thewikies.com/caniuse/video+audio+contenteditable.html?nocss&icon&text won't output anything if your browser supports the features. Is there any need for us to show a preview for it in that case? (at the moment I only have the live preview working/showing if JSON is selected)

**Comment by addyosmani** [comment]
Updated again (noticed @nimbupani made some UI changes):

Screenshot: ![Screenshot](http://addyosmani.com/gyazo/e36a9c.png)

PR: https://github.com/h5bp/caniuse/pull/33
