### ISSUE TITLE
Designer Proof

### ISSUE THREAD

**Issue by simurai** [h5bp/html5please-api#29]
I'm not really sure how to use the HTML version since it's just a link. But @nimbupani said that information is still missing. Anyways.. maybe that's the plan or maybe it's too late, but would it be a good idea to make it like how [Twitter buttons](https://twitter.com/about/resources/buttons#tweet) are used? Basically a wizard with a couple options that spits out a code snippet for people to paste onto their sites:

```
<div id="caniuse" data-support="audio+css-transitions" data-appearance="nocss+icon+text"></div>
<script> some code </script>
```

Then designers don't have to deal with JSON callback stuff. ;-)

**Comment by addyosmani** [comment]
@simurai I was thinking the exact same thing this afternoon. I believe Paul/Divya were aiming for a soft launch for the project on Monday/next week, but a basic wizard wouldn't be too difficult to bake into what's being done at the moment. Maybe something to be added later?

@nimbupani what do you think?

**Comment by simurai** [comment]
Or is there a good way to use the JSON version without jQuery? For simple CSS demos it seems a bit overkill to add jQuery just for that.

I tried it [like this](http://jsfiddle.net/simurai/vYutL/), which is pretty simple and seems to work fine.. but I believe `innerHTML` is risky because somebody could inject other scripts?

**Comment by addyosmani** [comment]
You don't have to use jQuery for it at all (as your test case demonstrated). If `innerHTML` in a concern, there's always `textContent`. See: https://developer.mozilla.org/en/DOM/element.innerHTML and then https://developer.mozilla.org/En/DOM/Node.textContent (limited to >IE9)

**Comment by sindresorhus** [comment]
@addyosmani That wouldn't work since <IE9 doesn't support textContent.
You could use innerText, but Firefox doesn't support that.
Something like this would work though:

``` javascript
if ( 'textContent' in document.body ) {
    elem.textContent = text;
} else {
    elem.innerText = text;
}
```

**Comment by addyosmani** [comment]
@sindresorhus indeed! As you correctly point out some additional special casing would be needed to get this working.

**Comment by simurai** [comment]
Hmm... but with `textContent` or `innerText`, the output is just the HTML string: http://jsfiddle.net/simurai/vYutL/2/

I don't mind using `innerHTML` but I'm just not sure if it could be harmful in this case with the callback? I think jQuery's `html()` uses it too, but only if it thinks it's save. 

If `innerHTML` is not save, the only other option would be DOM Scripting, right? But that's lots more code and it would be nice if it's part of the "one line" script.

**Comment by sindresorhus** [comment]
@simurai You're right. I only read Addy's comment.

If you're afraid of script injection your could just strip it before adding it to your element.

Wrote this now, only tested in Chrome, but should work everywhere:

``` javascript
function stripScripts( str ) {
    var tmp = document.createElement('div');
    tmp.innerHTML = str;
    var scripts = tmp.getElementsByTagName('script');
    while ( scripts.length ) {
        var script = scripts[0];
        script.parentNode.removeChild( script );
    }
    return tmp.innerHTML;
}

console.log( stripScripts('<div></div><script></script>') );
```

**Comment by addyosmani** [comment]
If there did end up being a builder for the snippet, having script stripping as an option to include/exclude could be useful. The question would be whether or not stripping was included as a sane default :)

**Comment by simurai** [comment]
Alright.. with the latest changes on http://h5bp.github.com/caniuse/ I think it's enough "Designer Proof". \o/ @sindresorhus Thanks for the stripScripts.

If you're interested.. I played around and tried to customize it a bit more:
1. In this example http://lab.simurai.com/flashlight/ (test in Opera), it degrades gracefully and the hover effect is still cool in Opera, so the CanIUse is just added at the bottom.
2. But in this case http://lab.simurai.com/carveme/ (test in Opera or Firefox), it doesn't make much sense, so CanIUse **replaces** the whole demo. It even adds a screenshot and custom text.
