### ISSUE TITLE
API

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#3]
API details:
http://sandbox.thewikies.com/caniuse/
conversation and details here: https://etherpad.mozilla.org/supportedbrowsersapi

We are not finalized on what the JSON payload is. 

We'd love to see some folks test our the API and apply to test pages. see #2

**Comment by AaronLayton** [comment]
I noticed in the Alternatives that it doesn't show the current browser your on? This is OK if your on something that auto updates (Chrome), but what would happen if the user is on IE6/7/8 ? Would IE show up as an alternative?

Would there also be support for showing experimental versions of the browsers?

Maybe have the version number that is recommended as well?
"alternatives":{
    "ie":{
        "name":"Internet Explorer",
        "version":"10"
        "url":"http:\/\/www.microsoft.com\/windows\/internet-explorer\/"
    }
}
