### ISSUE TITLE
Discussion 

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#4]
The history of this project is kind of displayed over here: https://github.com/paulirish/lazyweb-requests/issues/39

If you have any general feedback or discussion, chime in here or file a new ticket.

**Comment by AaronLayton** [comment]
Although there will be an API setup which will be great, will there also be a drop in feature something similar to this

http://jsfiddle.net/AaronLayton/fbths/
It's only a quick mock to get the idea, the code of course would be changed and built upon

I think it would be nice to just come up with a standard button, but not sure if this is a direction you want to take this in or if you just want to provide the functionality for others to create this sort of service?

**Comment by paulirish** [comment]
awesome mock! cc @jonathantneal

well you'd be able to do that, but it'd be funky to optimize.. it's more
likely you're going to get a few browsers returned to you that match your
featureset

so whatever this design is, it should scale from supporting 1-4 browsers as
opposed to one

dig?

**Comment by nimbupani** [comment]
The idea is to _not_ perpetuate monocultures with preferred browser listing. What the api would return is a set of options for users to choose from if there is no version of current browser to choose from.

**Comment by jonathantneal** [comment]
@AaronLayton, that looks great. Help me understand what you're asking for. Are you asking for a url that would generate the HTML/CSS for a button, perhaps even written within a document.write callback?

**Comment by AaronLayton** [comment]
@paulirish yeah it would be a task just get it to look right on every website but the general idea I thought was if I request a result from the json api and get returned a list of supporting browsers then I could list them in the hover state aswell.

The hover state would show what the developer had specified they need support for and list the supporting browsers under that. If the developer has given a preferred browser then that is what the icon would be next to the text. 

Thinking about it, my idea is starting to sound like a totally separate project haha.

**Comment by AaronLayton** [comment]
@jonathantneal My initial idea was to use the API to extend the idea with a service like in the mock. Something that a developer could just include on their page and the button be created for them. My example is really crude, only the design was of significance but something that could become the defacto solution for this kind of thing.

**Comment by jonathantneal** [comment]
@AaronLayton now that I understand what you want, I think it could be added in quite easily, with some default styles, but still customizable.

**Comment by paulirish** [comment]
Yeah i think the idea of a preferred browser is what we're trying to avoid
here.
The benefit for the developer is "i know the features. i dont want to track
which browsers support this."
See also: firefox removing support for websockets, etc.

That said I'd love to see a design thats as beautiful as this that scales
to show the full browser array that the API would return.

**Comment by AaronLayton** [comment]
@paulirish @jonathantneal I see what you mean. I will create a new mock and remove the preferred browser and show the supported browsers ;-)

**Comment by AaronLayton** [comment]
OK it's late here now so I am stopping and getting some sleep.

I have taken away the javascript from this mockup as it was meant to be more of a visual example. Let me know what you think
http://jsfiddle.net/AaronLayton/gFH3k/

**Comment by jonathantneal** [comment]
@AaronLayton, check it out, thoughts?

 [http://sandbox.thewikies.com/caniuse/canvas+json.html](http://sandbox.thewikies.com/caniuse/canvas+json.html)
 [http://sandbox.thewikies.com/caniuse/apng.html](http://sandbox.thewikies.com/caniuse/apng.html)

**Comment by jonathantneal** [comment]
Links updated.

**Comment by AaronLayton** [comment]
@jonathantneal That looks great :-D It works really well. I have just been testing it locally with lots of different test cases and I can see quite a few issues with the CSS but I am working through them now and will try and do a pull request for you

**Comment by jonathantneal** [comment]
Thanks @AaronLayton - it is your design! :)

Keep in mind, I would like to keep the CSS as simplified as possible to reduce the payload.

**Comment by AaronLayton** [comment]
No problem @jonathantneal All I have done upto yet is move some of the styles from '.caniuse-nfo' and put it into the hover state.

Because we was changing 'display:none' to 'display:block' on hover it overridden the transition. I have removed display none, set height to 0 with overflow hidden for normal state and then when hovered it will change the height auto and overflow auto.

**Comment by paulirish** [comment]
closing this ticket as we have others to carry the discussion
