### ISSUE TITLE
Current version of Opera Mini is wrong

### ISSUE THREAD

**Issue by miketaylr** [h5bp/html5please-api#46]
https://github.com/h5bp/html5please-api/blob/master/agents.json#L56

7.0 was released (on some platforms) today.

**Comment by nimbupani** [comment]
Fixed at 750ff1ef1a36328333226204b1bc196786dd1d0c

**Comment by nimbupani** [comment]
Fixed here 63b119ec6db5ebd3fec6e02692aeb80b1c771026
