### ISSUE TITLE
supported: unknown returned for canvas+webgl

### ISSUE THREAD

**Issue by Andypro1** [h5bp/html5please-api#49]
Accessing the URI http://api.html5please.com/canvas+webgl.json?callback=h5please&texticon&html&readable

returns {"supported":"unknown","html":""}

I tried the Modernizr version and it prints a log entry that indicates that it doesn't understand the feature "canvas+webgl."

**Comment by addyosmani** [comment]
Confirmed.

http://api.html5please.com/webgl.json?callback=h5pCaniuse&texticon&2&html&readable
http://api.html5please.com/audio+webgl.json?callback=h5please&texticon&html&readable
http://api.html5please.com/video+webgl.json?callback=h5please&texticon&html&readable

etc. all return the same response. Just so we're thorough, regular queries like:

http://api.html5please.com/video.json?callback=h5please&texticon&html&readable

are working fine at the moment.

**Comment by nimbupani** [comment]
This is because there is no universal webgl at the moment. http://caniuse.com/webgl Everything is dependent on the drivers you have in your machine. This is why it does not answer for webGL. You can use the unknown string to provide any other messaging you require.

**Comment by addyosmani** [comment]
Thanks for clearing that up @nimbupani! It of course makes sound sense in hindsight :)

**Comment by Andypro1** [comment]
@nimbupani - thanks for the explanation.  It seems that returning unknown for the browsers that partially support it makes sense, but shouldn't it still return a solid "no" for browsers like IE9 that definitely do not support it?

**Comment by nimbupani** [comment]
Yeah definitely, but right now we do not have such a granular view of the data. cc: @jonathantneal
