### ISSUE TITLE
Callback "html" is invalid

### ISSUE THREAD

**Issue by zcorpan** [h5bp/html5please-api#53]
"html": "&shy;<style>....... <\/style><div class=\"caniuse\">...."

This is invalid HTML. Why the &shy;? Since the next thing is a block box, it doesn't do anything anyway.

It should be more like:

"html": "<div class=\"caniuse\"><style scoped>....... <\/style>...."

**Comment by zcorpan** [comment]
http://krijnhoetmer.nl/irc-logs/whatwg/20120228#l-394

**Comment by drublic** [comment]
The `&shy;` was removed with ce1a548. The output is now in reversed order: HTML first, then CSS. I think this is what you suggested, right?

Thanks for reporting this, and sorry for all the time waiting for an answer!

**Comment by zcorpan** [comment]
No. Reverse order is still invalid HTML. Try http://html5.validator.nu/

It should be:

```
<div class="caniuse"><style scoped>styles...</style>...rest of html...</div>
```

I don't have permission to reopen, it seems.

**Comment by drublic** [comment]
Including the `style`-element before the rest of HTML caused other problems as explained in #64.
Using `scoped` seems like a good solution as the styles would not affect other elements outside the H5P-API-message. But as far as I know it's not supported in any browser yet…

**Comment by zcorpan** [comment]
AFAICT #64 talks about problems &shy; caused. I don't understand why the placement of style would affect rendering. That scoped is not supported in browsers yet shouldn't be much of a problem. The spec only allows style in body if it has a scoped attribute (and only in certain places).

**Comment by drublic** [comment]
So, after some time I've changed this: In [branch `scoped`](https://github.com/h5bp/html5please-api/tree/scoped) I've pushed two commits where I moved the styles into the `.caniuse`-block and scoped it.

@zcorpan Can you please review my commits 5d5b38c7 and f3485700? The output is valid now according to html5.validator.ru. Can you confirm this?

**Comment by zcorpan** [comment]
I'm not sure I follow what the code does exactly by just looking at those commits, but if the output validates then it should be OK.

**Comment by drublic** [comment]
f3485700 inserts a variable for styles in the output templates that is replaced in 5d5b38c7.
Thank you for your feedback :)

I'll close this issue now. If you come across problems, please feel free to re-open it.
