### ISSUE TITLE
Issue with webgl.json

### ISSUE THREAD

**Issue by paullewis** [h5bp/html5please-api#58]
Calling http://api.html5please.com/video+audio+webgl.json?callback=h5please&texticon as per the instructions results in:

```
{"supported":"unknown","html":""}
```

In fact it seems to be anything involving the webgl support.

**Comment by drublic** [comment]
Thanks for reporting, Paul!

We treat "partial support" as "no support". This is why there are no browsers which support WebGL according to our API (and also [caniuse-data](http://caniuse.com/#search=webgl)) and this results in the output you described.

We could change this and provide better feedback for a user. Such as "This is not fully supported in any browser but there are some which handle it kinda nice. Take one of these:".

What's your opinion on this @nimbupani?

**Comment by nimbupani** [comment]
Yeah what you said @drublic. @paullewis I thought http://get.webgl.org covered this space quite well :P but yeah, it is hard to test for support when support is so varied and dependent on drivers installed in addition to OSes and browsers.

**Comment by paullewis** [comment]
I think being pragmatic about it, that makes sense. In the case of
WebGL browsers do support it, although I take your point that it's not
full API support. But I would personally be happy with your suggestion
as something to present to users.

On 13 Mar 2012, at 19:07, Hans
reply@reply.github.com
wrote:

**Comment by drublic** [comment]
I've done some adjustments to get this idea working. I've commited these changes into my repo [over here](https://github.com/drublic/html5please-api). Can someone please check if it works correctly.

Two problems I am having with the commits:
- drublic/html5please-api@f4fda71 is a bit dirty and a better preset for `$support_array['partial']` might be `null` or something
- I've created two new "tests" with drublic/html5please-api@ff51059. The first one (`audio`) fails. It even failed when I run it locally without my commits. So maybe it's another bug. Can someone confirm this or is it just me?

I am not a PHP programmer, please keep that in mind when reviewing :))

**Comment by paulirish** [comment]
I think we need a solution here so I'd like to see drublic's fixes for this merged in

**Comment by nimbupani** [comment]
@jonathantneal could you test @drublic 's commits?

**Comment by jonathantneal** [comment]
Sure, wrapping my head around the conversation. :)

**Comment by drublic** [comment]
Any more thoughts and comments on this?

**Comment by paullewis** [comment]
Well I _was_ thinking it's good to do this because if Modernizr returns a nope on WebGL support for - say - IE9 it'd be better to say "you at least have a shot with one of these browsers" rather than "this isn't the technology you're looking for" and parking the user there.

But I assume the question was really aimed at @jonathantneal since he was testing the commit :)

**Comment by drublic** [comment]
I ment the PHP review, right.
So if there is no more comment on that, I'll push my changes to the repo and sync the gh-pages branch with the master. The master includes some more bugfixes we've developed a while ago.

**Comment by nimbupani** [comment]
:+1:

**Comment by drublic** [comment]
So I've pushed the data. I've not synced the master with the gh-pages-branch. So you can check out my changes and test them. Feedback appreciated.

**Comment by drublic** [comment]
So, looks like the API-page is already up to date. Maybe @jonathantneal's cron-job does this automatically. I'd suggest to pull the gh-pages-branch rather than the master.

I've synced the gh-pages with the master now. This should fix the issue.
