### ISSUE TITLE
Clientside Caching

### ISSUE THREAD

**Issue by AaronLayton** [h5bp/html5please-api#6]
Need to set correct response headers so that content is cached client side. This will ensure repeated requests to the html button wont incur more bandwidth.

Caching could also be turned on for the json / xml output aswell as the data wont be updated often

**Comment by jonathantneal** [comment]
We will need someone experienced with this in PHP.  I am NOT an expert. ... YET!

**Comment by AaronLayton** [comment]
Thanks H5BP ;-)

Something like this added to .htaccess 
If everything is cached for a day then that would cover most use cases. Anyone that returns on a second day should then get new data.

``` htaccess
<IfModule mod_expires.c>
  ExpiresActive on

# Default for all files
  ExpiresDefault                          "access plus 1 day"
  ExpiresByType text/html                 "access plus 1 day"

# Data
  ExpiresByType text/xml                  "access plus 1 day"
  ExpiresByType application/xml           "access plus 1 day"
  ExpiresByType application/json          "access plus 1 day"

# Media: images
  ExpiresByType image/png                 "access plus 1 month"

# CSS and JavaScript
  ExpiresByType text/css                  "access plus 1 dayr"
  ExpiresByType application/javascript    "access plus  1 day"

</IfModule>
```

**Comment by jonathantneal** [comment]
because i'm naive, should it be "access plus 1 day" where you wrote "access plus 1 dayr"?  I'm presuming that's a typo.

**Comment by AaronLayton** [comment]
Code now added to .htaccess so closing this issue
