### ISSUE TITLE
Problem with the generated widget

### ISSUE THREAD

**Issue by Keyamoon** [h5bp/html5please-api#61]
The generated widget code uses plus signs for separating features instead of spaces. Example:

<code>features: "localstorage+filereader+draganddrop+svg"</code>

Modernizr.html5please cannot split this using spaces:

<code>opts.features.split(' ');</code> (line 23 of <a href="https://github.com/h5bp/html5please-api/blob/master/modernizr.html5please.js">modernizr.html5please.js</a>)

Also, on line 46 of <a href="https://github.com/h5bp/html5please-api/blob/master/modernizr.html5please.js">modernizr.html5please.js</a>, parenthesis are missing which causes a wrong value for the url variable.

Even with these two issues fixed, my h5p-message shows undefined. (a.html is undefined.)

**Comment by Rowno** [comment]
I'm having the same issues. After fixing those 2 bugs in the widget Javascript, the API doesn't even return a `html` property.

**Comment by Keyamoon** [comment]
@Rowno I guess we are the first two users of this API!? How come nobody else tested it before?

**Comment by drublic** [comment]
This seems to be split up in #62 and #63. I'll close this for now. Thanks for reporting.
