### ISSUE TITLE
cssanimations.json data seems incomplete

### ISSUE THREAD

**Issue by tagawa** [h5bp/html5please-api#67]
Hi. Looking at the data provided in http://api.html5please.com/cssanimations.json it seems Opera is not mentioned as a browser that supports CSS3 animations. It's supported in Opera 12 (current version) - is this something that should be updated? Thanks.

**Comment by drublic** [comment]
Sure thing. Thanks for reporting this issue.
I checked this. With your PR #68 this is fixed. Thanks a bunch!
Please let us know if you detect further problems.

**Comment by tagawa** [comment]
Thank you - looks good. I'll try to keep an eye out for other issues.
