### ISSUE TITLE
docs page feedback

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please-api#9]
- can we use `<dt><dd>` combo for the API details?
- let's group options by HTML and JSON output. clarify that callback if your homeboy
- styling? should we style with caniuse's general flavor? 
- add some **In the Wild** examples (which we don't have yet)
- btw i added a bunch of text to explain wtf this is. also some `:target:` styling

**Comment by nimbupani** [comment]
BTW, I think @Fyrd is maintaining this at https://github.com/fyrd/caniuse/
