### ISSUE TITLE
Add Daniel Davis (@tagawa) in the `contribute` section

### ISSUE THREAD

**Issue by alrra** [h5bp/html5please-api#98]
@tagawa please add yourself to the `WITH` list, you more than deserve it!

![](https://cloud.githubusercontent.com/assets/1223565/3281524/be8fef12-f4b2-11e3-81d7-a302daa6c0a0.png)
## 

@tagawa thank you for all the great work you do maintaining this project, we really appreciate it! :+1:

**Comment by jonathantneal** [comment]
Seconded.

**Comment by tagawa** [comment]
That's very kind @alrra - I really appreciate knowing that people are using this.
Fixed ( https://github.com/h5bp/html5please-api/pull/99 ) and thanks @jonathantneal for merging.
